
# https://marketplace.visualstudio.com/items?itemName=sariftools.scans

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "scan"
    displayName: "KICS - Scan Ansible Playbook"
    jobs: 
      - job: "kics_scan"
        displayName: "Run KICS Scan"
        pool:
          vmImage: "ubuntu-latest"
        container: checkmarx/kics:debian
        steps:
          - script: |
              /app/bin/kics scan --ci -p ${PWD} -o ${PWD} --report-formats json,sarif,html --ignore-on-exit results
              cat results.json
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(System.DefaultWorkingDirectory)/results.*
              artifactName: CodeAnalysisLogs



  - stage: "scan_parse"
    displayName: "KICS - Parse Scan Resaults"
    jobs: 
      - job: "kics_scan_parse_result"
        displayName: "Check KICS Scan Resaults"
        pool:
          vmImage: "ubuntu-latest"
        steps:           
          - task: DownloadPipelineArtifact@2
            displayName: "Download the Security Scan Artifact Result"
            inputs:
              artifact: CodeAnalysisLogs
          - task: Bash@3
            displayName: "Check for MEDIUM issues in the scan result"
            inputs:
                failOnStderr: true
                targetType: 'inline'
                script: |
                  sarifFilePath="$(Pipeline.Workspace)/results.json"