
# https://marketplace.visualstudio.com/items?itemName=sariftools.scans

trigger:
- main

variables:
  breakSeverity: "MEDIUM"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "scan"
    displayName: "KICS - Scan Ansible Playbook"
    jobs: 
      - job: "kics_scan"
        displayName: "Run KICS Scan"
        pool:
          vmImage: "ubuntu-latest"
        container: checkmarx/kics:debian
        steps:
          - script: |
              mkdir -p $(System.DefaultWorkingDirectory)/output
              /app/bin/kics scan --ci -p ${PWD} -o ${PWD} --report-formats json,sarif,html --ignore-on-exit results
              mv results* $(System.DefaultWorkingDirectory)/output
              ls -lhat $(System.DefaultWorkingDirectory)/output
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(System.DefaultWorkingDirectory)/output
              artifactName: CodeAnalysisLogs

  - stage: "scan_parse"
    displayName: "KICS - Parse Scan Resaults"
    jobs: 
      - job: "kics_scan_parse_result"
        displayName: "Check KICS Scan Resaults"
        pool:
          vmImage: "ubuntu-latest"
        steps:           
          - task: DownloadPipelineArtifact@2
            displayName: "Download the Security Scan Artifact Result"
            inputs:
              artifact: CodeAnalysisLogs
          - task: Bash@3
            displayName: "Check for issues in the scan result"
            inputs:
                failOnStderr: true
                targetType: "inline"
                script: |
                  resultsFilePath="$(Pipeline.Workspace)/results.json"
                  BREAK=$(breakSeverity)
                  jq --arg BREAK "$BREAK" '.severity_counters[$BREAK] // 0' $resultsFilePath
                  noIssues=$(jq --arg BREAK "$BREAK" '.severity_counters[$BREAK] // 0' $resultsFilePath)
                  echo "Number of issues: $noIssues"
                  if [ "$noIssues" -ge 1 ]; then
                    echo "##[error]Pipeline failed due to more than $issueSeverity issue(s) found."
                    exit 1
                  else
                    echo "##[section]No issue found. Progressing with pipeline"
                  fi